# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (SUPABASE)
# ===============================
spring.datasource.url=jdbc:postgresql://db.yxkzooexberohwwdtplp.supabase.co:5432/postgres
spring.datasource.username=postgres
# ¡IMPORTANTE: Reemplaza TU_CONTRASEÑA_AQUI por tu contraseña real!
spring.datasource.password=${DB_PASSWORD}
# spring.datasource.password=Dragoncito154351234
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE HIBERNATE (JPA)
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect